### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by sneumann** [meowcat/MSnio#8]
MSnbase has `License: Artistic-2.0`
https://github.com/lgatto/MSnbase/blob/master/DESCRIPTION#L114
see also https://choosealicense.com/licenses/artistic-2.0/
Objections ? Alternatives ? Yours, Steffen

**Comment by meowcat** [comment]
I like Artistic, no objections from me. Any other opinions?

**Comment by michaelwitting** [comment]
Artistic is good for me.

**Comment by Treutler** [comment]
Artistic is also fine with me. I added the Artistic-2.0 license and other stuff to the DESCRIPTION in b02862dbe0a272628d8e4db09b9b12e5c982830a
